[package]
name = "workers-rs-benchmark"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker.workspace = true
web-sys.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-util.workspace = true
