[package]
name = "worker-macros"
version = "0.0.9"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
repository = "https://github.com/cloudflare/workers-rs/tree/main/worker-macros"
edition = "2018"
license = "Apache-2.0"
description = "Macros to support the `worker` crate and remove FFI boilerplate / conversion from user code."

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.68"
worker-sys = { path = "../worker-sys", version = "0.0.9" }
syn = "2.0.22"
proc-macro2 = "1.0.63"
quote = "1.0.29"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
wasm-bindgen-macro-support = "0.2.87"

[features]
queue = []
