[package]
name = "worker-macros"
version = "0.0.2"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
repository = "https://github.com/cloudflare/workers-rs/tree/main/worker-macros"
edition = "2018"
license = "Apache-2.0"
description = "Macros to support the `worker` crate and remove FFI boilerplate / conversion from user code."

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.51"
worker-sys = { path = "../worker-sys", version = "0.0.2" }
syn = "1.0.74"
proc-macro2 = "1.0.28"
quote = "1.0.9"
wasm-bindgen = "=0.2.78"
wasm-bindgen-futures = "0.4.28"
wasm-bindgen-macro-support = "0.2.78"
