[package]
name = "worker-sys"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2018"
version = "0.0.3"
license = "Apache-2.0"
repository = "https://github.com/cloudflare/workers-rs/tree/main/worker-sys"
description = "Low-level extern definitions / FFI bindings to the Cloudflare Workers JS Runtime."

[dependencies]
cfg-if = "0.1.2"
js-sys = "0.3.55"
wasm-bindgen = "=0.2.78"

[dependencies.web-sys]
version = "0.3.55"
features = [
    "ReadableStream",
    "RequestRedirect",
    "RequestInit",
    "ResponseInit",
    "FormData",
    "Blob",
]
