[package]
name = "worker-sys"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2018"
version = "0.0.4"
license = "Apache-2.0"
repository = "https://github.com/cloudflare/workers-rs/tree/main/worker-sys"
description = "Low-level extern definitions / FFI bindings to the Cloudflare Workers JS Runtime."

[dependencies]
cfg-if = "1.0.0"
futures = "0.3.21"
js-sys = "0.3.57"
pin-project = "1.0.10"
wasm-bindgen = "0.2.80"

[dependencies.web-sys]
version = "0.3.57"
features = [
    "ReadableStream",
    "RequestRedirect",
    "RequestInit",
    "FormData",
    "Blob",
    "BinaryType",
    "ErrorEvent",
    "MessageEvent",
    "CloseEvent",
    "ProgressEvent",
]
