name = "testing-rust-worker"
type = "javascript"
workers_dev = true
compatibility_date = "2021-08-27"
compatibility_flags = [ "formdata_parser_supports_files" ]

kv_namespaces = [
  { binding = "SOME_NAMESPACE", id = "", preview_id = "" },
  { binding = "FILE_SIZES", id = "" }
]

vars = { SOME_VARIABLE = "some value" }

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[build]
command = "rust-worker-build --release"

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"