[package]
name = "worker-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
libtest-mimic = "0.6.0"
tempfile = "3.3.0"
wasmparser = "0.99.0"
