name = "rust-rpc-client"
main = "build/index.js"
compatibility_date = "2024-04-05"

services = [
  { binding = "SERVER", service = "rust-rpc-server" }
]

[build]
command = "cargo install \"worker-build@^0.7\" && worker-build --release"