[package]
name = "worker"
version = "0.0.12"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
repository = "https://github.com/cloudflare/workers-rs"
edition = "2018"
keywords = ["serverless", "ffi", "workers", "wasm", "cloudflare"]
license = "Apache-2.0"
description = "A Rust SDK for writing Cloudflare Workers."
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
chrono = { version = "0.4.22", default-features = false, features = ["wasmbind"] }
chrono-tz = { version = "0.6.3", default-features = false }
futures-channel = "0.3.21"
futures-util = { version = "0.3.21", default-features = false }
http = "0.2.8"
js-sys = "0.3.57"
matchit = "0.4.2"
pin-project = "1.0.12"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
url = "2.2.2"
wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
serde-wasm-bindgen = "0.4.3"
wasm-streams = "0.2.3"
web-sys = "0.3.57"
worker-kv = "0.5.1"
worker-macros = { path = "../worker-macros", version = "0.0.6" }
worker-sys = { path = "../worker-sys", version = "0.0.6" }

[features]
queue = ["worker-macros/queue", "worker-sys/queue"]
d1 = ["worker-sys/d1"]