[package]
name = "worker"
version = "0.0.7"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
repository = "https://github.com/cloudflare/workers-rs"
edition = "2018"
keywords = ["serverless", "ffi", "workers", "wasm", "cloudflare"]
license = "Apache-2.0"
description = "A Rust SDK for writing Cloudflare Workers."
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
chrono = { version = "0.4", default-features = false, features = ["wasmbind"] }
chrono-tz = { version = "0.6", default-features = false }
futures = "0.3.16"
http = "0.2.4"
js-sys = "0.3.55"
matchit = "0.4.2"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
url = "2.2.2"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
worker-kv = "0.5.0"
worker-macros = { path = "../worker-macros", version = "0.0.2" }
worker-sys = { path = "../worker-sys", version = "0.0.2" }
