[package]
name = "tokio-postgres-on-workers"
version = "0.1.0"
edition = "2021"
resolver = "2"

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { workspace=true, features=["tokio-postgres"] }
tokio-postgres = { version="0.7", features=['js'], default-features=false }
