name: Tests
on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Check for errors
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: v17.4.0

      - name: Install packages
        run: |
          sudo apt update
          sudo apt clean
          sudo apt install -y build-essential libssl-dev netcat

      - name: Install miniflare
        run: npm install -g miniflare

      - name: Install wasmpack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run tests
        shell: bash
        working-directory: ./worker-sandbox
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          set -e

          echo "
          CF_API_TOKEN=\"$CF_API_TOKEN\"
          EXAMPLE_SECRET=\"example\"
          SOME_SECRET=\"secret!\"
          SOME_VARIABLE=\"some value\"
          " > .env

          # Start miniflare and register a trap to kill it once we're done
          miniflare --no-cf-fetch --no-update-check -c ./wrangler.toml &
          MINIFLARE_PID=$!
          trap "kill $MINIFLARE_PID" EXIT


          # Wait for port 8787 to open on miniflare by looping with netcat.
          echo "Waiting miniflare to launch on 8787..."
          while ! nc -z localhost 8787; do   
            sleep 0.1
          done

          cargo test
